sonar.projectKey=my_third_project_key
sonar.projectName=My Third Project
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=squ_0dc5361ec722f7562baba02ae4788995e731f2a1